spring.application.name=ms-productos
# Configuraci�n de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=linktic
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=Linktic

productos.db.getAllProducts=SELECT * FROM linktic.com_emprezabrez_getallproducts()
productos.db.get_producto_by_id=SELECT * FROM linktic.get_producto_by_id(?)

# Puerto del servidor
server.port=8080

springdoc.swagger-ui.path=/ms-productos/swagger-ui.html
springdoc.api-docs.path=/ms-productos/v1.0.0/api-docs
controller.properties.base-path=backend/v1/ms-productos
